### ISSUE TITLE
Docs: improve rendering for lists

### ISSUE THREAD

**Issue by bmicklea** [jozu-ai/kitops#102]
**Describe the problem you're trying to solve**
Bulleted and numbered lists in the docs are a little hard to read - they're not very indented and generally just kind of run together with the other text. See the `use-cases.md` as a good example.

**Describe the solution you'd like**
A little deeper indent on lists would help. Perhaps if there was more space between regular paragraphs and a little less at the top of the first item in a list that would help too. The docs need room to breathe! 😄 

**Describe alternatives you've considered**
Not using lists, but that seems extreme.

**Additional context**
n/a

**Comment by annigro** [comment]
We'll add a larger line spacing and a deeper indent. We'll also color the bullet points and numbered lists.
