### ISSUE TITLE
Homebrew tap distro

### ISSUE THREAD

**Issue by gorkem** [jozu-ai/kitops#113]

**Comment by bmicklea** [comment]
Maybe look into go Releaser?

**Comment by brett-hodges** [comment]
This is going to be more involved than I initially thought.  After building the brew distribution, it has to be evaluated and signed off by the Homebrew moderators.  I'm also going to need help building the brew distribution as it requires a build script.

**Comment by bmicklea** [comment]
This has been approved, if there are bugs we'll file them as separate issues.
