### ISSUE TITLE
Create KitOps Python libraries

### ISSUE THREAD

**Issue by gorkem** [jozu-ai/kitops#118]
**Describe the problem you're trying to solve**
To reduce adoption friction among data scientists we need a Python library that makes it trivial for someone to create a kitfile or build a ModelKit as part of their code.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bmicklea** [comment]
Scope of this is what @brett-hodges built into the Jupyter Notebook - creation and packing / unpacking.
