### ISSUE TITLE
Generate Dockerfile from `kitfile`

### ISSUE THREAD

**Issue by bmicklea** [jozu-ai/kitops#125]
**Describe the problem you're trying to solve**
Although I can build nearly any deployable artifact from the serialized model that is in the ModelKit, it's still work...

**Describe the solution you'd like**
Generate a Dockerfile based on my ModelKit and some basic criteria I provide.

**Describe alternatives you've considered**
Making Dockerfiles on my own from the `unpack`ed model in a ModelKit.

**Additional context**
none

**Comment by gorkem** [comment]
This is a duplicate/result of #131
