### ISSUE TITLE
Add way to clean up untagged modelkits/all local modelkits

### ISSUE THREAD

**Issue by bmicklea** [jozu-ai/kitops#126]
**Describe the problem you're trying to solve**
Once I have a number of ModelKits in my local repository, it can become annoying to have to clean them out one-by-one.

**Describe the solution you'd like**
Some kind of CLI command to do bulk removes.

**Comment by srikary12** [comment]
I'll be happy to work on this.

**Comment by amisevsk** [comment]
We've currently got two flags for this:
* Remove all untagged modelkits: `kit remove -a` or `kit remove --all`
* Remove all locally-stored modelkits: `kit remove -a -f` or `kit remove --all --force`

We can potentially add more ways of removing multiple modelkits, but this feels like the low-hanging fruit. Any suggestions?

**Comment by srikary12** [comment]
I think adding something based on regular expression would help.

**Comment by bmicklea** [comment]
I actually should have closed this issue when the `remove` command was expanded. @srikary12 if you think regular expressions would help can you create a new issue and explain the situations where it would be a meaningful improvement?
