### ISSUE TITLE
Incorrect or expired discord link on kitops website

### ISSUE THREAD

**Issue by Jwilliamsr** [jozu-ai/kitops#139]
**Describe the bug**
The links to join the KitOps discord have either expired or are directing to the old discord server. This needs to be updated.

I've created a link that will not expire: https://discord.gg/YyAfWnEg

**Comment by javisperez** [comment]
Hhmm weird 🤔 . I assume that the link expired because that was the latest invite link 🤷 . Anyway i'll update it with the one provided.
