### ISSUE TITLE
Tutorial: Fine-tuning LLMs using Kitops 

### ISSUE THREAD

**Issue by gorkem** [jozu-ai/kitops#169]
**Describe the problem you're trying to solve**
Reference material that shows how to use Kitops for fine-tuning LLMs 

**Describe the solution you'd like**
- Implement a fine-tuning solution that uses base models from ModelKits and repackages them. Use the dataset from Kitops repository (documents and code)
- Prepare a test set for validation 
- Demonstrate LoRA or QLoRA
- Show that tuning parameters can be stored on ModelKit config for efficiency

**Additional context**
We can take this solution as a permanent service for kitops.ml site.

**Comment by bmicklea** [comment]
Tutorial is live here: https://dev.to/kitops/fine-tune-your-first-large-language-model-llm-with-lora-llamacpp-and-kitops-in-5-easy-steps-1g7f
