### ISSUE TITLE
FAQ section for KitOps Site

### ISSUE THREAD

**Issue by Jwilliamsr** [jozu-ai/kitops#176]
Please design an FAQ section for the home page. This section should display the questions with collapsed answers. Let's start with 10 questions.

**Comment by annigro** [comment]
More than 1 Accordions can be open at the same time. (So the content doesn't jump)

**Comment by annigro** [comment]
@Jwilliamsr https://www.figma.com/file/COmS0qgbUJiOe24XguKOXI/KitOps---Landing-page?type=design&node-id=205%3A2866&mode=design&t=v7TxIXqVTUF1XAbl-1

**Comment by annigro** [comment]
@javisperez UX ticket for FAQ section
