### ISSUE TITLE
Support for proxies

### ISSUE THREAD

**Issue by gorkem** [jozu-ai/kitops#186]
**Describe the problem you're trying to solve**
It should be possible to use corporate proxy with kit CLI  

**Describe the solution you'd like**
kit CLI should respect the HTTP_PROXY* environment settings. It should also be possible to set proxies through CLI flags.

**Comment by srikary12** [comment]
I would like to work on this

**Comment by Jwilliamsr** [comment]
@srikary12 awesome, I've added you to the issue. If you need help, feel free to ping our team in Discord.

**Comment by srikary12** [comment]
I've made changes, How do I access cli to test the changes?
After running 
`go run .`
The kit cli exits

**Comment by srikary12** [comment]
@Jwilliamsr I've raised a PR. Let me know if any corrections are needed.
