### ISSUE TITLE
Site FAQ content

### ISSUE THREAD

**Issue by javisperez** [jozu-ai/kitops#198]
Need a FAQ section for the KitOps marketing site.

**Comment by bmicklea** [comment]
Writing up [questions and answers in this doc](https://docs.google.com/document/d/12xSfpxIrqH7Gu1HRbgFzKTIuymj2RfWTXXK0QH2Rk4Q/edit).

**Comment by bmicklea** [comment]
Requested feedback in KitOps Discord.

**Comment by Jwilliamsr** [comment]
Content approved and sent to Javis to implement
