### ISSUE TITLE
dev command (i)-icon text

### ISSUE THREAD

**Issue by annigro** [jozu-ai/kitops#216]
As a user, I would like to get more information about the terms used by dev command interface.
--> Create short information texts for the terms of the dev command. These texts will be displayed as a tooltip when the user clicks on an (i)-icon. 

Feel free to add or remove the (i)-icons (as they fit best).

[Google doc](https://docs.google.com/spreadsheets/d/1RcTDaxSPenA_BMv3lg4GN7ec3_57gog0s3RK5jjKEpc/edit?usp=sharing)

[Figma](https://www.figma.com/file/rk91xQQKvHZfcV3sqV4ReG/KitOps---dev-command?type=design&node-id=30%3A2699&mode=design&t=V4HXLN8W55gGN3RJ-1)

**Comment by annigro** [comment]
@javisperez Ticket includes info text.

**Comment by rajat-jozu** [comment]
Added the description for the Model Parameters in the chat interface : https://docs.google.com/spreadsheets/d/1RcTDaxSPenA_BMv3lg4GN7ec3_57gog0s3RK5jjKEpc/edit#gid=0

**Comment by annigro** [comment]
Hi @gorkem, here is the ticket with links to the text and layout for review.

**Comment by annigro** [comment]
Did Gorkem finish his review of the text?
