### ISSUE TITLE
Fixup for marketing site

### ISSUE THREAD

**Issue by bmicklea** [jozu-ai/kitops#228]
Some changes to the kitops.ml page:

**How does it work section**
Change text from "Kit is an open source MLOps tool that packages your AI model, datasets, code, and configuration into a ModelKit that data scientists and developers can use with their preferred tools" to:
> "Kit is a free open source MLOps tool that packages and versions your AI model, datasets, code, and configuration into a ModelKit that data scientists and developers can use with their preferred tools."

**Features section**
* Move it under the video
* Add a button under features: "See the Kit Workflow" link to https://kitops.ml/docs/use-cases.html#development-%F0%9F%A7%AA

**Get started section**
* Move to under the FAQ

**Comment by javisperez** [comment]
We also need to update the "Learn More" links in the `Key Features` section to these links:

Standard based packaging > https://kitops.ml/docs/modelkit/compatibility.html
Tamper-proof > https://kitops.ml/docs/modelkit/spec.html
Tags and Versions > https://kitops.ml/docs/cli/cli-reference.html#kit-tag
Automation for CI/CD > https://github.com/marketplace/actions/setup-kit-cli
