### ISSUE TITLE
Resumable Downloads in Kit CLI for Improved Reliability

### ISSUE THREAD

**Issue by gorkem** [jozu-ai/kitops#311]
**Describe the problem you're trying to solve**
Users often face unstable network conditions that can disrupt large blob downloads when using the Kit CLI, leading to incomplete transfers and inefficient bandwidth usage. It is crucial for the CLI to support resumable downloads to enhance user experience and reduce data wastage.

**Describe the solution you'd like**
Enable resumable downloads for `pull` and `unpack` commands in the Kit CLI, provided the remote registry supports this feature (e.g., using the Accept-Ranges header). This will allow the commands to automatically pause and resume blob transfers without restarting the entire download process.

**Describe alternatives you've considered**
Implementing a custom retry logic within the Kit CLI that automatically attempts to restart a download when it fails due to network issues.

Tasks

- [ ] Upload
- [ ] Download

**Comment by bmicklea** [comment]
NB: uploads will be more complex given the OCI spec so we'll consider whether this is needed later.
