### ISSUE TITLE
GTM: Add dev quotes to the KitOps site

### ISSUE THREAD

**Issue by Jwilliamsr** [jozu-ai/kitops#312]
- [ ] Create design for quotes section @annigro 
- [ ] Implement design on KitOps site @javisperez 

Quote #1

When you start producing many models, you need to have a way to store them, track where they are deployed, on what data they were trained on, which version of the runtime (if any) they are compatible with, and so on. It's inevitable for any company dealing with data science projects.
Marco Bignotti, Data Scientist at Orobix

Quote #2

The whole idea [of KitOps] is awesome... the development process used to be a struggle. By creating a middle ground between Devs and Data Scientists, you brought both sides together.
-- Paulo Cheadi Haddad Filho, Data Engineer @ Zwift

**Comment by annigro** [comment]
@Jwilliamsr  Where should this section be positioned?

**Comment by annigro** [comment]
[At the bottom of the file](https://www.figma.com/design/COmS0qgbUJiOe24XguKOXI/KitOps---Landing-page?node-id=205%3A2866&t=QOqyHhzB4lxFkOaP-1)

![Image](https://github.com/jozu-ai/kitops/assets/143543523/119a54a5-9ce0-4f9f-80f4-91a4a5ecd36c)

**Comment by Jwilliamsr** [comment]
Let's put it just above the FAQ. Two things:
1/ no need to put their face, let's just use title & company
2/ can we have them scrolling instead of stacked so it doesn't take up that much page room?

**Comment by annigro** [comment]
@Jwilliamsr like that?

<img width="1420" alt="Screenshot 2024-05-16 at 5 45 51 PM" src="https://github.com/jozu-ai/kitops/assets/143543523/ba9b2c4b-1378-456e-a241-f7478e4c81ed">

**Comment by Jwilliamsr** [comment]
I like V1. can we drop the opacity of the one that is not in focus?

**Comment by annigro** [comment]
@Jwilliamsr For sure.
<img width="1056" alt="Screenshot 2024-05-17 at 2 59 02 PM" src="https://github.com/jozu-ai/kitops/assets/143543523/b577019d-4e55-43b9-8a0c-864e28cad1d0">
<img width="1057" alt="Screenshot 2024-05-17 at 2 59 11 PM" src="https://github.com/jozu-ai/kitops/assets/143543523/6145fe4e-f5ee-4702-b958-264273c8d906">




 @javisperez  Can you do a little sliding animation? Changing quotes should be possible by clicking on the unhighlighted post or on the gray button below.

**Comment by javisperez** [comment]
@annigro sure
