### ISSUE TITLE
Docs formatting

### ISSUE THREAD

**Issue by bmicklea** [jozu-ai/kitops#320]
**Describe the bug**
Both hyperlinks and code snippets are the same color. It would be easier to read if hyperlinks were "brighter" or more noticeable than code snippets for formatting.

**To Reproduce**
Look at the Install page for a good example.

**Version**
Latest

**Comment by javisperez** [comment]
@annigro any color suggestion? this is the install page https://kitops.ml/docs/cli/installation.html

**Comment by annigro** [comment]
Ok, I am not the biggest fan of gold as a highlight color. I would prefer salmon or aero (cool support color we have in our back pocket).
<img width="1520" alt="Screenshot 2024-05-28 at 8 32 30 AM" src="https://github.com/jozu-ai/kitops/assets/143543523/4521fe98-9e7a-4c9a-88c3-f2be4431c135">
<img width="1507" alt="Screenshot 2024-05-28 at 8 32 08 AM" src="https://github.com/jozu-ai/kitops/assets/143543523/fc64771c-b373-4dca-bbc3-312d2fb66a88">
<img width="1527" alt="Screenshot 2024-05-28 at 8 33 00 AM" src="https://github.com/jozu-ai/kitops/assets/143543523/a624a349-a066-46a1-97e0-b50357925587">


Salmon: #FFA3AF
Aero: #00C3E2

**Comment by javisperez** [comment]
@bmicklea any preference between Salmon or Aero?

**Comment by javisperez** [comment]
also @annigro i assume that these links changes are for the content links only, not ALL the links, like the top navigation and the sidebar, right?

**Comment by bmicklea** [comment]
I prefer gold or aero. And don't change the color of sidebar highlight or top nav or else we will have just shifted the problem elsewhere :)
