### ISSUE TITLE
New quotes for the KitOps marketing website

### ISSUE THREAD

**Issue by bmicklea** [jozu-ai/kitops#325]
Quote 1:
“Currently we have a system that resembles half-MLOps but lacks data versioning tied to model versioning and configurations, and makes it difficult to deploy and keep track [of AI projects].”
- Majid, Data Scientist @ Siemens

Quote 2:
"As we have an open source first policy we are forced to go with tools like MLflow. But I really don’t like their 'opinionated' approach how practitioners should log artifacts. I like the idea of using existing best practices in the MLOps space."
- Niklas, MLOps Engineer @ Bundesdruckerei

**Comment by javisperez** [comment]
relates to #324

**Comment by javisperez** [comment]
@bmicklea are the square brackets here intentional: `"...keep track [of AI projects].”` ?
