### ISSUE TITLE
Kit CLI allows for multi-level Repository names to be "packed" in the Local Registry

### ISSUE THREAD

**Issue by brett-hodges** [jozu-ai/kitops#393]
**Describe the bug**
`kit pack` accepts Repository names with multiple-levels beyond what is expected.

**To Reproduce**
1.  Download the attached file: [kitfile-directory-test.tar.gz](https://github.com/user-attachments/files/16102531/kitfile-directory-test.tar.gz) to a directory of your choosing.
2. From a terminal window, extract the file with the command `tar -xvzf kitfile-directory-test.tar.gz`
3.`cd kit file-directory-test`
4. `kit pack . -t jozu.ml/repo-path/repo-subpath/mykitfile:latest`
5. Run `kit list` to confirm the addition of the ModelKit to the local registry even though it had too many levels in its Repository name.

**Version**
latest

**Additional context**

**Comment by amisevsk** [comment]
This is technically allowed by some repositories: https://github.com/users/amisevsk/packages/container/package/testone%2Ftesttwo%2Ftestthree

**Comment by brett-hodges** [comment]
Correct.  I can successfully `kit push` a ModelKit containing a multi-level repository path to ghcr.io; but, I can't successfully `kit push` a ModelKit containing a multi-level repository path to jozu.ml.  Instead, I get an ambiguous error message:

`Pushing jozu.ml/jozu-test/repo-level-testing/mymodel:latest`
`Failed to push: failed to copy to remote: Not Found (additional info: {"status":404,"error":"Not Found"})`

I'm closing this request in favor of:
1. Opening an Enhancement Request agains KitOps `kit push` to provide more clear error messaging when a repo fails to be pushed because its name contains multiple levels.
2. Opening an Enhancement Request for Jozu.ml to accept multi-level Repository names
