### ISSUE TITLE
KitOps / Red Hat blog

### ISSUE THREAD

**Issue by bmicklea** [jozu-ai/kitops#397]
Red Hat is interested in co-authoring a blog about KitOps and the RH portfolio. We will have to do most of the writing but can ear-mark sections where we need RH to author based on their expertise.

The overall flow should be:

1. Why KitOps is the best way to package models
2. How to package an IBM model from Red Hat InstructLab
3. Push ModelKit to Quay.io
4. Create `init container` from ModelKit
5. Deploy that to Red Hat OpenShift AI

Daniel Messer (Quay) will help push this through on their side. Jesse has other contacts already. From their perspective it's good to show the use of InstructLab, their models, Quay, and OpenShift AI.

**Comment by Jwilliamsr** [comment]
7/10 - Assigned to Dan and in progress

**Comment by bmicklea** [comment]
Now scheduled for release on RH Developer Portal for 16-Sep

**Comment by gorkem** [comment]
@Jwilliamsr Can we close this?
