### ISSUE TITLE
Add an option to authenticate via client certificate

### ISSUE THREAD

**Issue by notniknot** [jozu-ai/kitops#401]
**Describe the problem you're trying to solve**
It should be possible to use a personal client certificate (https://en.wikipedia.org/wiki/Client_certificate) for a reverse proxy in order to reach the image registry (Artifactory).

**Describe the solution you'd like**
Add a flag to specify a client cert for authentication and/or look for an envrionment variable that specifies the path to said certificate.

**Additional context**
At our company we cannot use KitOps from our local development environments because of the reverse proxy.

**Comment by amisevsk** [comment]
Hi @notniknot, I've opened PR https://github.com/jozu-ai/kitops/pull/402 that hopefully addresses your issue -- if you have a chance to take a look, your feedback would be appreciated!
