### ISSUE TITLE
Unpack hangs when files already exists and no overwrite flag is given

### ISSUE THREAD

**Issue by yichuan5** [jozu-ai/kitops#448]
**Describe the bug**
When unpacking for flag --code, if the code file already exists and does not provide -o . The unpacking hangs with progress bar, but does not prompt error. 

**Version**
Version: 0.3.2
Commit: 5e99ff38fcd5f4c75880a6516cc9e4f940435c26
Built: 2024-08-02T12:33:31Z
Go version: go1.21.6

**Additional context**
Intel 64bit
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"

**Comment by gorkem** [comment]
Confirmed. I see the same behaviour.

**Comment by amisevsk** [comment]
I just noticed this too last week and happened to tack a fix commit into https://github.com/jozu-ai/kitops/pull/446

@gorkem do you think we'll merge that PR soon? I can break out that commit to a separate PR if not.

Fixed by #446

**Comment by gorkem** [comment]
It is up to you. My review should be done by tomorrow morning
