### ISSUE TITLE
Add parameters field to datasets and code

### ISSUE THREAD

**Issue by amisevsk** [jozu-ai/kitops#478]
**Describe the problem you're trying to solve**
The `model` section of a Kitfile contains the parameters field for free-form additional data, to be consumed by other tooling. Such a field would be useful within datasets and code sections as well.

**Comment by RS-labhub** [comment]
Could you please elaborate and mention the file you're talking about?

**Comment by gorkem** [comment]
The mentioned `kitfile` is explained in this [documentation](https://kitops.ml/docs/kitfile/kf-overview.html). It is a manifest/config file that kit CLI uses to package AI/ML artifacts.  We have done a [similar feature](https://github.com/jozu-ai/kitops/commit/0afea7882afc2dacb0a146e9f155acbf7e20cbcd) for the `models` section of the Kitfile. This issues if for `datasets`

**Comment by RS-labhub** [comment]
I guess I could work on this... Could you please assign me this issue? If I face any trouble or think that this is out of my scope, I'll let you know!

**Comment by Jwilliamsr** [comment]
@RS-labhub, great. I've assigned the issue, if you have any questions feel free to chat in our community Discord.

**Comment by Jwilliamsr** [comment]
@RS-labhub I'm reopening this issue to add the hacktoberfest-accepted lable.

**Comment by RS-labhub** [comment]
Thanks @Jwilliamsr

**Comment by Jwilliamsr** [comment]
No worries, thank you for the contribution. Message me on Discord and we can get you some Hacktoberfest swag.

**Comment by RS-labhub** [comment]
> No worries, thank you for the contribution. Message me on Discord and we can get you some Hacktoberfest swag.

Ehh I didn't know about this.. That's a surprise... Thank you thank youuuuuuu!
