### ISSUE TITLE
Update KitOp Mailing List Form From Script to Static

### ISSUE THREAD

**Issue by Jwilliamsr** [jozu-ai/kitops#487]
The current KitOps mailing list signup is a script. It's converting at a very low rate and I believe this is due to script blockers. 

Instead, I'd like to make the form a static form that lives just below the buttons in the hero section "Install and Source Code"

**Comment by javisperez** [comment]
@Jwilliamsr do we want any title, paragraph or anything? or just an input saying "enter your email" and nothing else?

**Comment by Jwilliamsr** [comment]
Let's do "Stay informed about KitOps" + [Email address] + [Join the list]

**Comment by javisperez** [comment]
cool, thanks Jesse ill do it.

**Comment by Jwilliamsr** [comment]
@javisperez can I close this ticket?
