### ISSUE TITLE
Hacktoberfest issues (10)

### ISSUE THREAD

**Issue by Jwilliamsr** [jozu-ai/kitops#491]
To participate in Hacktoberfest, we need to create multiple issues that are tagged "hacktoberfest" for KitOps. These issues should range from good-first-issue to things that are more complex. 

Can everyone help create 2-3 issues? I'd like to have 1-2 that are more front end focused, I'd like to have 1-2 that are modelkit focused (possibly sourcing new models for quick starts?), a few that are CLI focused, and maybe on that is CI/CD focused?

**Comment by bmicklea** [comment]
@Jwilliamsr they need a label called hacktoberfest, right?

**Comment by Jwilliamsr** [comment]
@bmicklea here's a good example of what we need to do

https://github.com/freeCodeCamp/freeCodeCamp/issues/56170

**Comment by bmicklea** [comment]
Issues have been tagged
