### ISSUE TITLE
Update Getting Started doc with Instructions to Manually Create Repositories

### ISSUE THREAD

**Issue by brett-hodges** [jozu-ai/kitops#493]
**Describe the bug**
Repositories are no longer automatically created when pushing using the Kit CLI, so the doc needs to be updated to include the steps related to manually creating a Repository before pushing a tagged ModelKit.

**Comment by amisevsk** [comment]
It depends on the platform you are pushing to; dockerhub et. al. will create repositories on push, while jozu.ml will not. I don't know that the kitops documentation is the place for how to create repositories on jozu.ml.

**Comment by bmicklea** [comment]
I will just make a note that some registries will require you to create the repository in advance. But should we auto-create the repository in Webscale Registry? Seems like a good feature... @amisevsk

**Comment by amisevsk** [comment]
We should file an issue internally for more discussion
