### ISSUE TITLE
Make errors more explicit

### ISSUE THREAD

**Issue by bmicklea** [jozu-ai/kitops#510]
**Describe the problem you're trying to solve**
When trying to `kit push` a ModelKit to a repository that doesn't exist you get a very general (and not super helpful) error:
>  [ERROR] Failed to push: failed to copy to remote: HEAD : response status code 401: Unauthorized

**Describe the solution you'd like**
We can't know what exactly the error was, but we can make the message more suggestive. Something like:
>  [ERROR] Failed to push: failed to copy to remote: HEAD : response status code 401: Unauthorized. Check that the organizaiton and repository you're pushing to exists and that you have write permissions.

**Additional context**
This is primarily about helping with the user experience when there are errors, remembering that some KitOps users won't be experienced software developers.

**Comment by TusharMohapatra07** [comment]
I would like to work on this issue.

**Comment by nitesh2920** [comment]
If this issueis still open can I work on it @bmicklea

**Comment by Jwilliamsr** [comment]
@nitesh2920 the issue is still open, however, @TusharMohapatra07 already requested to work on it. Feel free to checkout our other #491 Hacktoberfest issues

**Comment by RS-labhub** [comment]
Close this issue.. 🥺
