### ISSUE TITLE
Some Typing and grammatical mistakes in Documention 

### ISSUE THREAD

**Issue by FarukhS52** [jozu-ai/kitops#526]
Describe the problem you're trying to solve
There are a number of little typos, grammar mistakes, and other minor issues throughout the docs. Fixing these mistakes will help readers see that the project is being professionally handled and thoroughly reviewed / used.

Describe the solution you'd like
Correction of the various issues across the README and primary docs (getting started, next steps, etc...)

**Comment by bmicklea** [comment]
Thanks @FarukhS52 we've merged your PR so I'll close this issue as complete. Congratulations on your first KitOps contribution! I hope it's not the last 😄
