### ISSUE TITLE
Update Dagger Modules and Publish to Daggerverse.dev

### ISSUE THREAD

**Issue by gorkem** [jozu-ai/kitops#531]
We need to update the existing modules in the [daggerverse](https://github.com/jozu-ai/daggerverse) repository. Following the updates, these modules should be published to [daggerverse.dev/publish](https://daggerverse.dev/publish) to make them accessible to larger audience.

## Updates needed
- [ ] Dependency update and setup dependabot
- [ ] Setup CI for modules
- [ ] Automated testing
- [ ] Update documentation if needed

**Comment by srikary12** [comment]
Would be happy to help @gorkem on this.

**Comment by gorkem** [comment]
All dagger modules are published to daggerverse

https://daggerverse.dev/mod/github.com/jozu-ai/daggerverse/gguf
https://daggerverse.dev/mod/github.com/jozu-ai/daggerverse/huggingface
https://daggerverse.dev/mod/github.com/jozu-ai/daggerverse/kit
