### ISSUE TITLE
Swtich to llamafile for `dev` command. 

### ISSUE THREAD

**Issue by gorkem** [jozu-ai/kitops#532]
To streamline the development workflow and improve cross-platform compatibility, we propose implementing the `dev` command using llamafile. Llamafile offers the advantage of providing a single binary compatible with all major platforms, simplifying integration and maintenance for the project.

Benefits
* Simplifies builds
* Adds support for linux
* Adds support for windows
* Adds some nice features

Challenges
* Kit CLI becomes 160MB instead of 10MB

Llamafile is working on a new server implementation that should speed it up by 3-4x.

**Comment by bmicklea** [comment]
@gorkem is this complete now?
