### ISSUE TITLE
Kubernetes-ready

### ISSUE THREAD

**Issue by sean-3** [jozu-ai/kitops#534]
When is Kubernetes-ready coming?

**Comment by bmicklea** [comment]
Depends on what you're looking for. Today you can store ModelKits in a container registry like Harbor or Quay which are integrated into the K8s ecosystem.

To make ModelKits more deployable, we've been delayed on that. But Jozu, another organization (Jozu.ml) is working on a converter to turn a ModelKit into a:
* container
* init container

So they should work with Kube.

**Comment by bmicklea** [comment]
@sean-3 is there a specific Kube use case you're looking for?

**Comment by RS-labhub** [comment]
This is not a bug!

**Comment by sean-3** [comment]
> @sean-3 is there a specific Kube use case you're looking for?您正在寻找特定的 Kube 用例吗？


I want to deploy modelkit to kubernetes cluster

**Comment by bmicklea** [comment]
Ok, I think we have everything we need for this via `init` containers, but need to document it. We'll look at it in more depth this sprint.

**Comment by bmicklea** [comment]
@sean-3 is there a specific Kube distro / version you're using?

**Comment by bmicklea** [comment]
@sean-3 you can find docs on how to get containers and Kubernetes deployments here: https://kitops.ml/docs/deploy.html
