### ISSUE TITLE
Update Code of Conduct for Clarity and Inclusivity

### ISSUE THREAD

**Issue by Mayank8881** [jozu-ai/kitops#536]
**Describe the bug**  
The Code of Conduct requires updates for clarity and inclusivity to better serve the project community.

**To Reproduce**  
1. Review the current Code of Conduct.
2. Identify areas lacking clarity or inclusivity.
3. Compare with the proposed revisions in the pull request.

**Version**  
Latest

**Additional context**  
The updates aim to enhance readability and ensure a welcoming environment for all participants.

**Comment by nayan135** [comment]
assign me i can help

**Comment by bmicklea** [comment]
Closing now that PR is closed
