### ISSUE TITLE
Demo: use ModelKit with MLFlow

### ISSUE THREAD

**Issue by bmicklea** [jozu-ai/kitops#545]
Lots of our users are working with MLFlow, but would like to see how to use ModelKits with it. Doing a short demo showing how a set of files saved in MLFlow can be turned into a ModelKit might help.

A blog or article would help too.

**Comment by bmicklea** [comment]
Ideally we would use an LLM for this so we could follow it with the runnable container demo. Minimally we can use the titanic xample from the notebook demo.

**Comment by brett-hodges** [comment]
Note from @bmicklea  :

Ok, go back to the MLFlow and I think the thing to do is:

- Find a project where the dataset is a flat file and stored on disk
- Write a Kitfile for the project
- Do the demo using the magic Kitfile
