### ISSUE TITLE
@@!~!Suivez en direct la cérémonie du Ballon d'Or 2024

### ISSUE THREAD

**Issue by vizakenjaro** [jozu-ai/kitops#568]
DIRECT. Ballon d’or 2024 : « Aucun joueur ni club ne sait », assurent les organisateurs, suivez la cérémonie
A la surprise générale, le Real Madrid a décidé de boycotter la 68e cérémonie du Ballon d’or, qui se déroulera ce lundi 28 octobre au Théâtre du Châtelet à Paris. Contre toute attente, Vinicius Junior ne devrait en effet pas être le vainqueur, le club refuse de se rendre « là où il n’est pas respecté ».

[𝐖𝐀𝐓𝐂𝐇 🔴▶️ 𝐁𝐚𝐥𝐥𝐨𝐧 𝐝'𝐎𝐫 𝟐𝟎𝟐𝟒 𝐋𝐈𝐕𝐄](https://shows.procast.live/?refd_by=clicktvt)

[𝐖𝐀𝐓𝐂𝐇 🔴▶️ 𝐁𝐚𝐥𝐥𝐨𝐧 𝐝'𝐎𝐫 𝟐𝟎𝟐𝟒 𝐋𝐈𝐕𝐄](https://shows.procast.live/?refd_by=clicktvt)

[𝐖𝐀𝐓𝐂𝐇 🔴▶️ 𝐁𝐚𝐥𝐥𝐨𝐧 𝐝'𝐎𝐫 𝟐𝟎𝟐𝟒 𝐋𝐈𝐕𝐄](https://shows.procast.live/?refd_by=clicktvt)

Suivez en direct la cérémonie du Ballon d'Or 2024 avec Flashscore France !

C'est le grand jour. Ce lundi 28 octobre, le monde du football connaîtra le nom du Ballon d'Or 2024. Suivez la cérémonie avec nous tout au long de la soirée sur Flashscore France.
18h20 : Bien qu'il soit parfois décrié, il n'y a aucun doute sur le fait qu'il est un grand gardien, Emiliano Martinez se classe eu 18ᵉ rang.

EN DIRECT Ballon d'or 2024 : Le Real Madrid fait du boudin car le trophée va lui échapper, Saliba 24e
FOOTBALL•Le lauréat n'est plus au courant qu'il a remporté le trophée avant la cérémonie, ce qui redistribue les cartes pour l'édition 2024

Le gagnant des votes au Ballon d'or 2024 sera désigné ce lundi au théâtre du Châtelet .Un journaliste de chacun des 100 meilleurs pays au classement FIFA a voté afin d'élire les meilleurs de chaque catégorie, chez les filles et les garçons.
La cérémonie sera à suivre sur L'Équipe TV à partir de 16h45. Le classement sera progressivement dévoilé jusqu'à la fin de la cérémonie, prévue pour 22h45.
Le vainqueur n'est plus mis au courant en amont, comme lors des années précédentes. Cette années, les pronostics penchent en faveur de Vinicius, porté par la grandeur du Real Madrid et Rodri, champion d'Angleterre avec City et champion d'Europe avec la Roja.
Côté tricolore, deux joueurs seulement font partie des noinés : Kylian Mbappé, toujours dans le top 10 depuis son irruption en 2017, et William Saliba.

18h20:

commun-mauvais
« Le Ballon d'or n'existe plus pour nous »
Le Real pas du tout dans la demi-mesure. On dirait un gosse de 3 ans qui s'est fait piquer son camion de pompier. Selon Marca, et c'est signé par un journaliste qui a ses entrées à Bernabeu, le Real Madrid a même dédicé d'annuler l'émission spéciale programmée sur la chaîne du club, considérant qu'on est bien foutus de sa gueule ces dernières semaines en lui disant sous le manteau que c'était pour « Vini ». A la place une retransmission du classico de samedi peut-être ?

18h10:

Pendant que le Real boude, sachez que les places ont commencé à tomber
Saliba est 24e, ce qui est pas si mal considérant qu'il laisse six mecs derrière, dont Hummels et Dobvyk, récompensés pour leur superbe saison avec Dortmund et Gérone

17h25:

Le Chiringuito en PLS alors que c'est visiblement un Espagnol qui va gagner. Ce pays est incompréhensible

17h15:

Pour être sûr que ça n'arrive pas, les organisateurs l'ont enlevé de la liste des nominés
Dans le doute, ils le donneront à Messi.

Joedire

17h13

Assez d'accord avec toi. Le Real manque vraiment de classe sur coup-là, même si on peut comprendre qu'entre Rodri et Carvajal, la logique aurait réclamé de récompenser le second, qui a gagné et marqué en finale de C1.
Le Real, ils sont comme Vlad "ouin ouin les autres n'ont pas le droit de gagner ouin ouin"

Durandil vs les pro Poutine

**Comment by Jwilliamsr** [comment]
spam, closing
