### ISSUE TITLE
Add dedicated CI/CD section to KitOps docs (Dagger and Jenkins) 

### ISSUE THREAD

**Issue by Jwilliamsr** [jozu-ai/kitops#583]
Add an expanded section to the kitops documentation that covers the CI/CD use case. This should include our daggerverse modules and our use case around Jenkins.

**Comment by Jwilliamsr** [comment]
Add the KitOps GitHub action as well

**Comment by bmicklea** [comment]
Will be addressed by:

1. #586 
2. #588

**Comment by bmicklea** [comment]
I assumed adding two PRs would close the issue with AND but seems to do it on OR...boo.
