### ISSUE TITLE
Add Tail Option to kit dev logs Command

### ISSUE THREAD

**Issue by gorkem** [jozu-ai/kitops#591]
**Describe the problem you're trying to solve**
Currently, the `kit dev logs command` retrieves and displays logs from the last or current development session. However, it lacks the capability to continuously stream logs in real time. Developers often need to monitor logs live to track the progress of ongoing tasks, identify issues as they occur, and ensure that their development environment is functioning correctly. 

**Describe the solution you'd like**
Introduce a --tail (or -f) flag to the kit dev logs command that, when used, continuously streams and displays new log entries as they are generated. This behavior mimics the functionality of the Unix tail -f command, providing a seamless and integrated way to monitor logs in real time.

**Behaviour:** When the flag is used, kit dev logs enters a streaming mode, continuously fetching and displaying new log entries. The tailing continues until the user manually terminates the command (e.g., via Ctrl+C).

**Comment by srikary12** [comment]
Will get this fixed today.

**Comment by srikary12** [comment]
As there is no log rotation, I've added custom tailing.
