### ISSUE TITLE
Add previous & next buttons to docs pages

### ISSUE THREAD

**Issue by bmicklea** [jozu-ai/kitops#592]
**Describe the problem you're trying to solve**
The docs pages are getting a bit long partly because it's not necessarily obvious to the reader where they would go to next.

**Describe the solution you'd like**
There are a number of docs sites that use:
1. Previous & Next page buttons at the bottom of each docs page - this helps users know where to continue their journey
2. Page hierarchies in the left nav - for example [Dagger's API page begins collapsed](https://docs.dagger.io/api) but when you click on it you see a bunch of sub-pages. This would be helpful for some of our sections where details could be progressively exposed.

(1) seems more useful and important right now. (2) is interesting but may not be needed yet - dropped it in here more to see if there was any thoughts/discussion on it right now.

**Comment by javisperez** [comment]
Wont fix as this is already part of Vitepress default's settings
