### ISSUE TITLE
Migrate KitOps from GitHub pages to some other provider

### ISSUE THREAD

**Issue by Jwilliamsr** [jozu-ai/kitops#615]
To improve SEO, indexing, and bot activity we need to migrate kitops.ml off of github pages to cloudflare

**Comment by javisperez** [comment]
Related noted: I had a quick, small talk about it with @gorkem and we might have a few issues that might prevent us from using Cloudflare (but of course, he's the expert, so he has the final saying) but for the sake of keeping the choices open, i have edited the title as we might end up not using Cloudflare but using something else instead.

**Comment by javisperez** [comment]
Here's a list in the official Vitepress documentation about different platforms that we could consider in case Cloudflare is not an option: https://vitepress.dev/guide/deploy#platform-guides

**Comment by Jwilliamsr** [comment]
@javisperez I don't think it really matters where we move it to, I was just under the impression that cloudflare was the easiest since we are already using it.

**Comment by javisperez** [comment]
> @javisperez I don't think it really matters where we move it to, I was just under the impression that cloudflare was the easiest since we are already using it.

Yes, i just wanted to mention it in the issue for visibility and information.
