### ISSUE TITLE
Update default storage paths 

### ISSUE THREAD

**Issue by amisevsk** [jozu-ai/kitops#74]
### Description

Currently, `kit` defaults to storing everything within `$HOME/.kitops`. Since the `.kitops` directory is not intended for direct user access (and instead serves as general storage for OCI artifacts, credentials, etc.), it makes more sense to use more standard directories for each operating system:

* Linux/MacOS: `$HOME/.local/share/kitops`
* Windows: `%LOCALAPPDATA%/kitops`

In addition, it would be convenient to respect an environment variable -- e.g. `$KITOPS_HOME` -- for overriding this default (in addition to the `--config` flag). This would allow using an alternate storage path for multiple commands (or setting a default value system wide) without needing to add the `--config` flag to each command.

**Comment by gorkem** [comment]
@amisevsk this one is done now right?

**Comment by amisevsk** [comment]
Yup, completed in https://github.com/jozu-ai/kitops/pull/89
